# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: loopd

before:
  hooks:
    - go mod tidy

builds:
  - id: loopd
    main: .
    binary: loopd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Exclude Windows ARM64 (limited support)
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - plugins/loopd-loop-export/loopd.js
      - plugins/loopd-markdown-importer/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: stuffbucket
    name: loopd
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: loopd
    repository:
      owner: stuffbucket
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/stuffbucket/loopd"
    description: "Export Loop pages to portable Markdown with images preserved"
    license: "MIT"
    install: |
      bin.install "loopd"
      # Install plugin files for --copy-script and --export-plugin
      (share/"loopd/plugins/loopd-loop-export").install "plugins/loopd-loop-export/loopd.js"
      (share/"loopd/plugins/loopd-markdown-importer").install Dir["plugins/loopd-markdown-importer/*"]
    test: |
      system "#{bin}/loopd", "--version"
